// auth.js — Auth / Setup UI Flow

const AuthView = {
    init() {
        document.getElementById('form-setup').addEventListener('submit', async (e) => {
            e.preventDefault();
            const name = document.getElementById('setup-name').value;
            const btn = e.target.querySelector('button');
            const origHTML = btn.innerHTML;

            btn.innerHTML = '<span>Setting up...</span>';
            btn.disabled = true;

            try {
                // p2pIdentity is already generated by App.init(), we just update the profile
                await updateIdentityProfile({ name });
                App.currentUser = await getOrCreateIdentity(); // Reload identity
                
                // Show main view
                this.clearInputs();
                await App.initializeMainView();
            } catch (err) {
                console.error('Setup failed:', err);
                this.showError('setup-error', err.message);
            } finally {
                btn.innerHTML = origHTML;
                btn.disabled = false;
            }
        });
    },

    clearInputs() {
        document.getElementById('setup-name').value = '';
        this.showError('setup-error', '');
    },

    showError(elementId, message) {
        document.getElementById(elementId).textContent = message;
    }
};
